#ifndef __LIST_H__
#define __LIST_H__

#define LIST_CODE_OK 0

#define LIST_ERROR_NULL_POINTER -1
#define LIST_ERROR_MEMMORY_ALLOCATION -2

#define LIST_ITERATOR_ERROR_LIST_NOT_DEFINED -1
#define LIST_ITERATOR_ERROR_INDEX_OUT_OF_BOUNDRY -2

struct list;



#endif // !__LIST_H__